version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  backend:
    build:
      context: ../back
      dockerfile: ../docker/Dockerfile.backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../front
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  cypress:
    image: cypress/included:14.3.2
    working_dir: /e2e
    volumes:
      - ../front:/e2e
    entrypoint: ["npx", "cypress", "run", "--browser", "chrome"]
    depends_on:
      - frontend
