version: '3.8'

services:
  frontend:
    build: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    command: npm start

  backend:
    build: ./back
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - ./docker/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  cypress:
    image: cypress/included:14.3.3
    depends_on:
      - frontend
      - backend
    environment:
      - CYPRESS_baseUrl=http://frontend:4200
    volumes:
      - ./e2e:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "open"] # GUI mode via VNC