name: E2E Tests Static (Angular build + Cypress + Coverage)

on:
  workflow_dispatch:
    inputs:
      use-cloud:
        description: "Record to Cypress Cloud?"
        required: false
        default: "false"
        type: choice
        options: ["true", "false"]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 📦 Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: 📦 Install dependencies
        working-directory: front
        run: |
          npm ci
          npm install --save-dev serve @cypress/code-coverage istanbul-lib-coverage istanbul-lib-instrument

      - name: 🔧 Build Angular App with source maps
        working-directory: front
        run: |
          npm run build -- --source-map

      - name: 🚀 Serve built app (with fallback)
        working-directory: front
        run: |
          npx serve -s dist/front -l 4200 &
          sleep 10

      - name: ✅ Run Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: front
          wait-on: 'http://localhost:4200'
          browser: chrome
          headless: true
          record: ${{ github.event.inputs.use-cloud == 'true' }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📊 Generate Code Coverage Report
        working-directory: front
        run: |
          npx nyc report --reporter=lcov --reporter=text-summary --report-dir=coverage
        continue-on-error: true

      - name: 📤 Upload Code Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-coverage
          path: front/coverage/

      - name: 🔒 Enforce minimum coverage threshold
        working-directory: front
        run: |
          npx nyc check-coverage --lines 80 --functions 80 --branches 70 --statements 80

      - name: 📝 Add Cypress + Coverage Summary
        working-directory: front
        run: |
          echo "## ✅ Résumé du job E2E (build statique)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "<h2>🧪 Cypress Results</h2>" >> $GITHUB_STEP_SUMMARY
          echo "<table>" >> $GITHUB_STEP_SUMMARY
          echo "<tr><th>Status</th><th>Passed ✅</th><th>Failed ❌</th><th>Skipped ⏭️</th><th>Duration ⏱️</th></tr>" >> $GITHUB_STEP_SUMMARY
          echo "<tr><td>Run</td><td>--</td><td>--</td><td>--</td><td>--</td></tr>" >> $GITHUB_STEP_SUMMARY
          echo "</table>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## 📊 Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          npx nyc report --reporter=text-summary >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY